version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.8.3
    steps:
      - checkout # check out the code in the project directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run:
          command: pipenv install
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          command: pipenv run tests
          name: Unit Test