version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.8.3
    steps:
      - checkout # check out the code in the project directory
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: print('running')
